spring:
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    # 开启模板缓存（默认值： true ）
    cache: false
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 要运⽤于模板之上的模板模式。另⻅ StandardTemplate-ModeHandlers( 默认值： HTML5)
    mode: LEGACYHTML5
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    #Content-Type 的值（默认值： text/html ）
    servlet:
      content-type: text/html
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html

#  pagehelper分页
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

#下面这些内容是为了让MyBatis映射
mybatis-plus:
  #指定Mybatis的Mapper文件
  mapper-locations: classpath*:cn/rails/physicals/mapper/xml/*.xml
  #指定Mybatis的实体目录
  type-aliases-package: cn.rails.physicals.entity
  #返回值没有字段及数据时，字段对应返回null
  configuration:
    call-setters-on-nulls: true


#移动端交互密钥
DES_KEY: 19491001


##单点登录密钥-生产环境
#tjPublicKey: '{"kty":"RSA","kid":"7386798824867824049","alg":"RS256","n":"y66QBu4NfMlFB8FrXvOlw3xll3vyMMeQgsw4I1TjElPrMm_ptwRFIbW5xndoL-Qy9BQTadJhA8IYM_kwyW_QyUdUJzkbf2mA9Ugc4qXGo_GPAbL6qOCfeqgPP1gKgpB4sEWI_g2dxw8-Xx6eX-D5J3jpXdx6EcmYNORivLJ1yEI25k-OBZV9SWFautHd0MQHf83EsOVOGlLT7DCW7nvNYpMeQ6uwMuSNCRd2CvsrUXDbyzWQUHNhNF0dkKMwjBE8rs4P1WSh61JehgJMvuX5KBhljYej46jMAvF1GEGS1hdjfbVTmOke8KcDDj9FwhNqSVOmhXtU2rCgfcvtahJtow","e":"AQAB"}'

#单点登录密钥-测试环境
tjPublicKey: '{"kty":"RSA","kid":"726803164639100032","alg":"RS256","n":"sOBQg0sYpxF9foifAaSM4KB-LQ-BDUi-u2eUr8FiuMgSTeQpLhndeSK9U5We_uxx69mZ1yzezVKRskW3CQOzXGKoiHOGjPjZU_YG1OL7p6T2AdBoS8pCFnqoFky7xiMXL1ELiJ6ezoN6mbIFSpy13i2nd0TCnJzC2op7fYqegM8pNM5OrMkzc_xqLJWwN9z2HWxbHW0mtgLsx-cfRzoGD6GWhWpnaU287GXOj8aAH0xMc4eJoJ9jxq8zb2wQVUtrJgO8xkZTwKqPdzx9qRM7D98zAJHdSCYz27AunWf2ddVMo5ixvngSe4IAf7BnvX2zyIR90Pot3-WdrHi-WYdzWw","e":"AQAB"}'


#linux文件存放位置
#uploadFilePath: /usr/local/

#windows文件存放位置
uploadFilePath: D:\











